{
  flake.modules.homeManager.yazi =
    {
      pkgs,
      ...
    }:
    {
      # terminal file manager
      programs.yazi = {
        enable = true;
        package = pkgs.yazi;
        # Changing working directory when exiting Yazi
        enableBashIntegration = true;
        enableZshIntegration = true;
        shellWrapperName = "yz";
        settings = {
          mgr = {
            show_hidden = true;
            sort_dir_first = true;
          };

          # Open files via xdg-mime by default (mimeapps.list generated by programs/de [nd]/xdg-mimes.nix).
          # env -u must strip NIXOS_XDG_OPEN_USE_PORTAL, otherwise xdg-open routes through
          # org.freedesktop.portal.OpenURI and pops the GTK app chooser.
          # To switch apps, press O and pick "Open with..." to summon that dialog explicitly.
          opener = {
            open = [
              {
                run = "env -u NIXOS_XDG_OPEN_USE_PORTAL xdg-open %s1";
                desc = "Open";
              }
            ];
            play = [
              {
                run = "env -u NIXOS_XDG_OPEN_USE_PORTAL xdg-open %s1";
                desc = "Open";
                orphan = true;
              }
              {
                run = "mediainfo %s1; echo 'Press enter to exit'; read _";
                desc = "Show media info";
                block = true;
              }
            ];
            reveal = [
              {
                run = "env -u NIXOS_XDG_OPEN_USE_PORTAL xdg-open %d1";
                desc = "Reveal in file manager";
              }
              {
                run = "clear; exiftool %s1; echo 'Press enter to exit'; read _";
                desc = "Show EXIF";
                block = true;
              }
            ];
            zed = [
              {
                run = "zeditor --new %s";
                desc = "Open with Zed";
                orphan = true;
              }
            ];
            extract = [
              {
                run = "ya pub extract --list %s";
                desc = "Extract";
              }
            ];
            # Call xdg-desktop-portal's OpenURI.OpenFile; ask=true forces the GTK chooser
            pick = [
              {
                run = "${pkgs.glib.bin}/bin/gdbus call --session --dest org.freedesktop.portal.Desktop --object-path /org/freedesktop/portal/desktop --method org.freedesktop.portal.OpenURI.OpenFile --timeout 5 '' 3 \"{'ask': <true>}\" 3< %s1";
                desc = "Open with...";
                orphan = true;
              }
            ];
          };

          # Every rule must include pick so "Open with..." shows up in the O list
          # prepend_rules take precedence over preset rules; append_rules fall back (they replace the preset url="*")
          open = {
            prepend_rules = [
              # Directories: url ending in / matches dirs only (yazi mime is folder/*)
              {
                url = "*/";
                use = [
                  "open"
                  "zed"
                  "pick"
                  "reveal"
                ];
              }
              {
                mime = "text/html";
                use = [
                  "open"
                  "pick"
                  "reveal"
                ];
              }
              {
                mime = "text/{csv,rtf}";
                use = [
                  "open"
                  "pick"
                  "reveal"
                ];
              }
              {
                mime = "text/*";
                use = [
                  "edit"
                  "open"
                  "zed"
                  "pick"
                  "reveal"
                ];
              }
              {
                mime = "application/{json,ndjson,javascript,wine-extension-ini}";
                use = [
                  "edit"
                  "open"
                  "zed"
                  "pick"
                  "reveal"
                ];
              }
              {
                mime = "image/*";
                use = [
                  "open"
                  "pick"
                  "reveal"
                ];
              }
              {
                mime = "{audio,video}/*";
                use = [
                  "play"
                  "pick"
                  "reveal"
                ];
              }
              {
                mime = "inode/empty";
                use = [
                  "edit"
                  "open"
                  "zed"
                  "pick"
                  "reveal"
                ];
              }
              {
                mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}";
                use = [
                  "extract"
                  "open"
                  "pick"
                  "reveal"
                ];
              }
            ];
            append_rules = [
              # Fallback: office / pdf / executables not matched above
              {
                url = "*";
                use = [
                  "open"
                  "pick"
                  "reveal"
                ];
              }
            ];
          };
        };
      };
    };
}
