[audio]
enable_overdrive = true
enable_sounds = true

[bar.default]
background_opacity = 0.87999998033046722
capsule = true
capsule_opacity = 0.40000000000000002
center = [ "group:g2" ]
concave_edge_corners = true
end = [
    "tray",
    "clipboard",
    "wallpaper",
    "network",
    "bluetooth",
    "input_volume",
    "volume",
    "brightness",
    "battery",
    "notifications",
    "clock",
    "session"
]
margin_edge = 0.0
margin_ends = 0.0
padding = 6
radius = 0
radius_bottom_left = 16
radius_bottom_right = 16
start = [ "launcher", "workspaces", "group:g1", "weather", "nix-monitor", "active_window", "status" ]

    [[bar.default.capsule_group]]
    fill = "surface_variant"
    id = "g1"
    members = [ "cpu", "temp", "ram" ]
    opacity = 0.40000000596046448
    padding = 6.0

    [[bar.default.capsule_group]]
    fill = "surface_variant"
    id = "g2"
    members = [ "media" ]
    opacity = 0.40000000596046448
    padding = 6.0

[dock]
active_monitor_only = true
auto_hide = true
enabled = true
icon_size = 44
reserve_space = false

[location]
auto_locate = false

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000007",
    "lockscreen-widget-0000000000000005",
    "lockscreen-widget-0000000000000008"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 720.0
    cy = 728.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.0
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = false
        show_media = false
        show_session_buttons = false
        show_unlock_hint = false
        show_weather = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 240.0
    box_width = 368.0
    cx = 304.0
    cy = 608.0
    output = "eDP-1"
    rotation = 0.0
    type = "weather"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background_opacity = 0.0
        show_forecast = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 224.0
    box_width = 352.0
    cx = 720.0
    cy = 256.0
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background_opacity = 0.0
        clock_style = "digital"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000005]
    box_height = 48.0
    box_width = 272.0
    cx = 720.0
    cy = 792.0
    output = "eDP-1"
    rotation = -0.0
    type = "label"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000005.settings]
        background_opacity = 0.0
        title = "LINK START ！"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000007]
    box_height = 192.38671875
    box_width = 194.671875
    cx = 720.0
    cy = 575.806640625
    output = "eDP-1"
    rotation = 0.0
    type = "sticker"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000007.settings]
        background_opacity = 0.0
        image_path = "/home/zno/Pictures/头像/2026-04-18_09-25-08.webp"
        opacity = 1.0

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000008]
    box_height = 0.0
    box_width = 0.0
    cx = 1171.0
    cy = 624.0
    output = "eDP-1"
    rotation = 0.0
    type = "media_player"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000008.settings]
        background = true
        background_color = "surface"
        background_opacity = 0.80000000000000004
        background_padding = 10
        background_radius = 12
        color = "on_surface"
        font_family = ""
        hide_when_no_media = true
        layout = "horizontal"
        shadow = true

[osd]
position = "top_right"

[plugins]
enabled = []

[shell]
avatar_path = "/home/zno/Pictures/头像/2026-04-18_09-25-08.webp"
clipboard_history_max_entries = 500
font_family = "LXGW WenKai Screen"
polkit_agent = true
settings_show_advanced = true
telemetry_enabled = false

    [shell.panel]
    open_near_click_control_center = true
    session_placement = "floating"
    session_position = "center"

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "suspend"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "5"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "6"
    variant = "destructive"

    [shell.shadow]
    alpha = 0.89999997988343239

[theme]
builtin = "Tokyo-Night"
community_palette = "Tokyo Night Moon"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-tonal-spot"

[wallpaper]
directory = "/home/zno/Pictures/wallpapers/others"

    [wallpaper.default]
    path = "/home/zno/Pictures/wallpapers/others/anime-girls-cat-girl-white-rose-nature-kawaii-skirt.jpg"

    [wallpaper.last]
    path = "/home/zno/Pictures/wallpapers/others/anime-girls-cat-girl-white-rose-nature-kawaii-skirt.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/zno/Pictures/wallpapers/others/anime-girls-cat-girl-white-rose-nature-kawaii-skirt.jpg"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/zno/Pictures/wallpapers/others/wallhaven-qr3175_3840x2160.png"
    theme_mode = "dark"
    wallpaper_scheme = "m3-tonal-spot"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/zno/Pictures/wallpapers/others/wallpaper666.png"
    theme_mode = "dark"
    wallpaper_scheme = "m3-content"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/zno/Pictures/wallpapers/others/anime-girls-cat-girl-white-rose-nature-kawaii-skirt.jpg"
    theme_mode = "dark"
    wallpaper_scheme = "m3-content"

[widget.active_window]
capsule = true
capsule_opacity = 0.40000000000000002
max_length = 150.0

[widget.audio_visualizer]
bands = 20
capsule = true
capsule_opacity = 0.40000000000000002
width = 100.0

[widget.battery]
show_label = false

[widget.brightness]
show_label = false

[widget.clock]
format = "{:%H:%M %A, %m/%d}"

[widget.cpu]
capsule = true
capsule_opacity = 0.40000000000000002
show_label = false

[widget.input_volume]
show_label = false

[widget.launcher]
capsule = true
capsule_opacity = 0.40000000000000002
custom_image = "/home/zno/Pictures/nixos_logo_icon.svg"
scale = 1.1499999999999999

[widget.media]
capsule = true
capsule_opacity = 0.40000000000000002
hide_when_no_media = true
max_length = 150.0
title_scroll = "on_hover"

[widget.network]
show_label = false

[widget.network_rx]
capsule = true
capsule_opacity = 0.40000000000000002
show_label = false

[widget.network_tx]
capsule = true
capsule_opacity = 0.40000000000000002
show_label = false

[widget.nix-monitor]
show_text = false
type = "avivbintangaringga/nix-monitor:nix-monitor"
up_to_date_color = "primary"

[widget.ram]
capsule = true
capsule_opacity = 0.40000000000000002
show_label = false

[widget.session]
color = "#CE9680"
scale = 1.1499999999999999

[widget.status]
type = "pozzoo/hassio:status"

[widget.sysmon]
capsule = true

[widget.temp]
capsule = true
capsule_opacity = 0.40000000000000002
show_label = false

[widget.tray]
drawer = true
drawer_columns = 5

[widget.volume]
show_label = false

[widget.wallpaper]
capsule = true
capsule_opacity = 0.40000000000000002

[widget.weather]
show_condition = false

[widget.workspaces]
display = "none"
