[bar.default]
background_opacity = 0.87999998033046722
capsule = true
capsule_opacity = 0.40000000000000002
center = [ "group:g2" ]
end = [
    "tray",
    "clipboard",
    "network",
    "bluetooth",
    "input_volume",
    "volume",
    "brightness",
    "power_profile",
    "battery",
    "notifications",
    "clock",
    "session"
]
margin_edge = 0.0
margin_ends = 0.0
padding = 6
radius = 0
start = [ "launcher", "workspaces", "group:g1", "active_window" ]

    [[bar.default.capsule_group]]
    fill = "surface_variant"
    id = "g1"
    members = [ "cpu", "temp", "ram" ]
    opacity = 0.40000000596046448
    padding = 6.0

    [[bar.default.capsule_group]]
    fill = "surface_variant"
    id = "g2"
    members = [ "media", "audio_visualizer" ]
    opacity = 0.40000000596046448
    padding = 6.0

[dock]
active_monitor_only = true
auto_hide = true
enabled = true
icon_size = 44

[shell]
avatar_path = "/home/zno/Pictures/头像/2026-04-18_09-25-08.webp"
font_family = "LXGW WenKai Screen"
polkit_agent = true
settings_show_advanced = true
telemetry_enabled = false

    [shell.panel]
    session_placement = "centered"

[theme]
source = "wallpaper"
wallpaper_scheme = "m3-tonal-spot"

[wallpaper]
directory = "/home/zno/Pictures/wallpapers/others"

    [wallpaper.default]
    path = "/home/zno/Pictures/wallpapers/others/anime-girls-cat-girl-white-rose-nature-kawaii-skirt.jpg"

    [wallpaper.last]
    path = "/home/zno/Pictures/wallpapers/others/anime-girls-cat-girl-white-rose-nature-kawaii-skirt.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/zno/Pictures/wallpapers/others/anime-girls-cat-girl-white-rose-nature-kawaii-skirt.jpg"

[widget.active_window]
capsule = true
capsule_opacity = 0.40000000000000002
max_length = 150.0

[widget.audio_visualizer]
bands = 20
capsule = true
capsule_opacity = 0.40000000000000002
width = 100.0

[widget.battery]
show_label = false

[widget.brightness]
show_label = false

[widget.clock]
format = "{:%H:%M %A, %m/%d}"

[widget.cpu]
capsule = true
capsule_opacity = 0.40000000000000002
show_label = false

[widget.input_volume]
show_label = false

[widget.launcher]
capsule = true
capsule_opacity = 0.40000000000000002
custom_image = "/home/zno/Pictures/nixos_logo_icon.svg"
scale = 1.1499999999999999

[widget.media]
capsule = true
capsule_opacity = 0.40000000000000002
hide_when_no_media = true
max_length = 150.0
title_scroll = "on_hover"

[widget.network]
show_label = false

[widget.network_rx]
capsule = true
capsule_opacity = 0.40000000000000002
show_label = false

[widget.network_tx]
capsule = true
capsule_opacity = 0.40000000000000002
show_label = false

[widget.ram]
capsule = true
capsule_opacity = 0.40000000000000002
show_label = false

[widget.session]
color = "#CE9680"
scale = 1.1499999999999999

[widget.sysmon]
capsule = true

[widget.temp]
capsule = true
capsule_opacity = 0.40000000000000002
show_label = false

[widget.tray]
drawer = true
drawer_columns = 5

[widget.volume]
show_label = false

[widget.wallpaper]
capsule = true
capsule_opacity = 0.40000000000000002

[widget.workspaces]
display = "none"